name: webofthings
services:
  db:
    container_name: wot_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: wotpass
      POSTGRES_USER: wotusr
      POSTGRES_DB: wot
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data