# Set the project name
name: WebOfThings

services:
  api:
    image: node:20.15
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy
        restart: true
    working_dir: /app
    volumes:
     - ./:/app
    environment:
     - APP_PORT=3005
     - NODE_ENV=development
     - DB_HOST=api.wot.internal
     - DB_NAME=wot
     - DB_USER=wotusr
     - DB_PASS=wotpass
     - SEC_SALT_ROUNDS=10
     - SEC_SALT=m4k3sur3ToCh4ng3M3
     - JWT_SECRET_TOKEN=S3cur3En0ugh4D3v!
     - JWT_SECRET_REFRESH=L3tsD0M0r3F0rSa!
     - JWT_DEFAULT_EXPIRY=5m
     - JWT_DEFAULT_EXPIRY_REFRESH=1d
     - LOG_DIR=logs
     - LOG_HTTP=http.log
     - LOG_APP=app.log
     - LOG_ERROR=error.log
     - LOG_ROTATION=1d
    command: bash -c "npm ci && npm run dev"

  db:
    image: postgres:14-alpine
    ports: 
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=wotpass
      - POSTGRES_USER=wotusr
      - POSTGRES_DB=wot
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 30s
      retries: 5
      start_period: 80s